sudo: required
  services:
    - docker

  before_install:
    - docker -t deepthisagar90/new-image1image2 -f build  Dockerfile .

  script:
    docker run -e CI=true deepthisagar90/new-image1image2 npm run test -- -- coverage
